### ISSUE TITLE
2017-01-09 게임 기획서_01

### ISSUE THREAD

**Issue by nanakorn** [FeatherHub/Subway#2]
게임 진행을 위한 글은 종류가 나뉘지만, 목적은 비슷하다. 플레이어의 게임 접속도를 높이기 위한 장치로 사용된다.

1. 게임의 스토리를 설명하는 글
 
  - 캐릭터에 대한 글(캐릭터의 특성 및 배경을 설명하는 글)
  - 다음 스테이지(공간)으로 넘어가도록 동기부여를 하는 글

2. 게임 캐릭터(플레이어)에게 보내는 글. 즉, 제작자의 의도를 직접 보내는 글.

플레이어는 모니터 화면을 바라보며 게임을 한다. 플레이어의 시점은 모니터 속 캐릭터와 캐릭터의 주변에 분포된 시각 이미지에 집중한다.
모니터 속 플레이되는 게임은 누군가 인위적으로 제작한 가상의 공간이다. 가상의 공간은 다양한 함의를 가지기도 하고, 무의미할 때도 있다.
가상의 공간이 예상 가능한 함의를 가지게 되는 것은 실제 세상과 유비적으로 연결되어있기 때문이다. 플레이어는 모니터 밖에서 플레이한다. 그는 모니터 밖의 서사에 종속되어있는 인간이고, 게임은 모니터 밖의 세상을 기반으로 제작될 수도 있고, 아닐 수도 있다. 적당한 은유는 함의를 키울 수 있다. 그렇기에 모니터 속 서사가 명확하게 구축되면 될수록 모니터 밖과는 결을 달리하려는 시도가 될 수 있다. 우리는 모니터 밖과 안의 중간지점을 게임의 공간으로 상정한 채 제작을 시작한다. 그런 시도로 플레이어와 캐릭터의 접속도가 높아지기를 바란다. 다른 게임과 다르게 'subway’는 스테이지(공간)을 이동하는 것에 특별한 제한이 없다. 즉 퀘스트가 없기 때문에 플레이에 난항을 초래할 수 있다. 
 퀘스트는 플레이어에게 숙제를 내는 것과 같다. 플레이어는 자신에게 주어진 숙제를 완수하며 게임을 이어나간다. 그 숙제는 반드시 완수해야한다. 왜냐하면 일종의 이정표와 같기 때문이다. 메이플스토리를 처음시작하고, 전직을 할 수 있는 레벨이 되었을 때 전직 퀘스트가 날아온다. 그 퀘스트를 완수하면 캐릭터(플레이어)는 새로운 직업을 획득하게 되고, 게임을 이어나갈 수 있게 된다. 그리고 획득한 새로운 직업의 연계퀘스트를 통하여 게임 속 스토리를 자연스럽게 습득하며 본인이 플레이하고 있는 가상공간에 대한 이해도가 높아진다. 가상공간의 이해도가 높아지면 그곳에서의 생활이 일정 수준으로 자연스러워진다. 그렇게 플레이를 지속할 수 있고, 게임 속 캐릭터에 동화된다. 게임 속 퀘스트는 일종의 사회화 과정으로 이해되며, 과연 그것을 배제한 상태에서 어떤 장치가 필요한지 생각해봐야 한다. 퀘스트의 빈자리를 무엇으로 채울 수 있을까?
 캐릭터는 부분적으로 멸망한 세상에서 살아가고 있다. 그는 달성할 수 없는 목표를 바라보며 움직인다. 대단한 목표의식으로 인한 움직임이 아니다. 그저 개인의 만족을 위한 헛걸음에 가깝다. 플레이어는 그런 캐릭터를 조종한다. 과연 플레이어는 알고 있을까? 자신(플레이어의 모니터 속 분신)이 달성해야 할 목표가 처음부터 불가능하다는걸. 그리고 제작자는 그것을 알려줘야 할까? 플레이 중간중간 제작자는 플레이어에게 길을 잡아줄 수 있다. 그것의 적절한 방식이 퀘스트라고 상정하자. 우리의 게임에 공란은 퀘스트다. 게임의 배경지식에 대한 정보공유의 완급조절권은 제작자에게 있다. 우리는 어느 정도의 정보를 제공해줘야 할까? 그리고 정보를 제공할때 어떤 방식으로 제공해줘야 할까?
 만약 제작자가 플레이어에게 아주 기본적인 게임의 정보(예를 들어 장르)만 제공한 상태에서 플레이어는 어떤 모습을 보일까? 자유를 획득한 상태에서 플레이어는 어디까지 갈 수 있을까?

**Comment by FeatherHub** [comment]
카카오톡으로
